spring.application.name=app
# DATASOURCE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# En caso de ser primera vez ejecutando el proyecto colocar create en vez de update
spring.jpa.hibernate.ddl-auto=${SQL_DDL_AUTO}
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
